package com.mobiocean.util;

import com.mobiocean.beans.SendAttendanceBean;
import com.mobiocean.beans.SendConveyanceBean;
import com.mobiocean.beans.SendConveyanceImageBean;
import com.mobiocean.mobidb.SOSandTheftInfoStruct;
import com.mobiocean.util.LKONagarNigam.CalendarSync;

import org.sn.beans.AppGroupBean;
import org.sn.beans.ContactListBean;
import org.sn.beans.EnabledExtraFeatureBean;
import org.sn.beans.ProfileInfoBean;
import org.sn.beans.ResponseModel;
import org.sn.beans.SecuredStorageApiModel;
import org.sn.beans.SensorListBean;
import org.sn.beans.VpnStatusBean;
import org.sn.beans.WebListBean;

import java.util.ArrayList;

import retrofit2.Call;
import retrofit2.http.Body;
import retrofit2.http.GET;
import retrofit2.http.POST;
import retrofit2.http.Query;

// This interface doesn't have a regular implementation! Instead the
// implementation is generated by Retrofit.

public interface AanwlaService 
{
	@GET("api/ContactList/GetSyncDateTime")
	Call<ArrayList<InsertIntoContactSync>> GetSyncDateTime(@Query("AppId") String Appid);

	@GET("api/ContactList/GetContactList")
	Call<ArrayList<InsertIntoContactSync>> listContactAccordingTodate(@Query("AppId") String Appid ,@Query("Date") String date);

	@GET("api/ChatApp/GetSyncDateTime")
	Call<ArrayList<CalendarSync>> listCalendarDate(@Query("AppId") String Appid);

	@GET("api/ChatApp/GetCalenderList")
	Call<ArrayList<CalendarSync>> listCalendarAccordingTodate(@Query("AppId") String Appid ,@Query("Date") String date);

	@POST("api/ContactList/InsertIntoContactList")
	Call<String> sendContactList(@Query("Id") String Id,@Body ContactStruct mContactStruct);
	
	@POST("api/ChatApp/SyncCalendar")
	Call<String> sendCalendarList(@Body CalendarSyncServer mCalendarSyncServer);
	
	@POST("api/AppLogs/AppLogs")
	Call<String> sendApplicationLogs(@Body GameLogs mGameLogs);

	@GET("api/Update/CheckUpdates")
	Call<ArrayList<UpdateFromServer>> getWhatIsUpdated(@Query("Id") String Appid);

	@POST("api/Update/SetAck")
	Call<String> sendUpdateAck(@Body UpdateFromServer mUpdateFromServer);

	@POST("api/File/Insert")
	Call<String> sendFileInfo(@Body SOSandTheftInfoStruct mSOSandTheftInfoStruct);
	
	@POST("api/Log/BulkSMS")
	Call<String> sendSmsBackUp(@Body Sms mSms);
	
	@POST("api/Sos/InsertSosContactDetails")
	Call<String> sendSosContacts(@Body SOSContacts mSOSContacts);

	@POST("api/AppSupport/Insert")
	Call<String> updateReport(@Body SendReport sendReport);
	
	@GET("api/sos/GetSosContactList")
	Call<ArrayList<SOSContacts.SosContactsClass>> getSosContacts(@Query("appID") String Appid);

	@GET("api/DeviceInfo/CheckRemoteLockPin")
	Call<String> getLockPin(@Query("Id") String Id);

	@POST("api/Attendance/InsertAttendenceDetails")
	Call<String> getAttendance(@Body SendAttendanceBean sendAttendanceBean);

	@POST("api/Conveyance/InsertConveyanceDetails")
	Call<String> sendConveyance(@Body SendConveyanceBean sendConveyanceBean);

	@POST("api/ConveyanceRemark/InsertRemarkIntoConveyance")
	Call<String> sendConveyanceRemarks(@Body SendConveyanceImageBean sendConveyanceImageBean);

	@GET("api/AppStatus/ChkVersion")
	Call<String> getUpdate(@Query("AppId") String appId, @Query("Version") String version);

	@GET("api/Subscribe/ChkExpiry")
	Call<String> checkSubscription(@Query("appId") String appId);

	@GET("api/User/CheckClient")
	Call<Integer> verifyUserInfo(@Query("MyAppId") String myAppId,@Query("AppId") String appId, @Query("ClientName") String clientName);

	//Narayanan New Edit
	@GET("api/Policy/MobileNo")
	Call<ArrayList<ContactListBean>> getContactList(@Query("AppId") String Appid, @Query("IsForUpdate") String IsForUpdate);

	@GET("api/Policy/GetWifiSensorDtls")
	Call<ArrayList<SensorListBean>> getSensorList(@Query("appId") String Id);

	@GET("api/Policy/GetActivatedProfile")
	Call<Integer> getActiveProfileId(@Query("AppId") String Appid);

	@GET("api/Policy/GetProfileList")
	Call<ArrayList<ProfileInfoBean>> getProfileDetails(@Query("AppId") String Appid, @Query("IsForUpdate") String IsForUpdate);

	@GET("api/Policy/GetProfile")
	Call<ArrayList<ProfileInfoBean>> getProfileList(@Query("AppId") String Appid,@Query("IsForUpdate") String IsForUpdate);

	@GET("api/Policy/GetAppGroup")
	Call<ArrayList<AppGroupBean>> getAppGroups(@Query("AppId") String Appid, @Query("IsForUpdate") String IsForUpdate);

	@GET("api/Policy/WebSite")
	Call<ArrayList<WebListBean>> getWebsites(@Query("AppId") String Appid, @Query("IsForUpdate") String IsForUpdate);

	@GET("api/policy/AttendanceEnable")
	Call<EnabledExtraFeatureBean> getEnabledExtraFeature(@Query("appId") String Id);

	@GET("api/policy/VPNEnable")
	Call<VpnStatusBean> getVpnDetails(@Query("appId") String Id);

	@GET("api/FileUpload/GetFileListByUser")
	Call<ResponseModel<ArrayList<SecuredStorageApiModel>>> getFileList(@Query("AppId") String Id, @Query("IsUpdate") int isUpdate, @Query("Index") int Index);

}
